name: KoinlyXP build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install build environment
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel pipenv
          pipenv install -d
      - name: Build
        run: |
          pipenv run python -m build .
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: koinlyxp-dist
          path: dist/

